// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain.proto

package types // import "github.com/inn4science/exonum-go/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	ProposerId           uint32   `protobuf:"varint,1,opt,name=proposer_id,json=proposerId,proto3" json:"proposer_id,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	TxCount              uint32   `protobuf:"varint,3,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	PrevHash             *Hash    `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	TxHash               *Hash    `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	StateHash            *Hash    `protobuf:"bytes,6,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_60255c37bab97d9c, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetProposerId() uint32 {
	if m != nil {
		return m.ProposerId
	}
	return 0
}

func (m *Block) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetTxCount() uint32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *Block) GetPrevHash() *Hash {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *Block) GetTxHash() *Hash {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *Block) GetStateHash() *Hash {
	if m != nil {
		return m.StateHash
	}
	return nil
}

type ConfigReference struct {
	ActualFrom           uint64   `protobuf:"varint,1,opt,name=actual_from,json=actualFrom,proto3" json:"actual_from,omitempty"`
	CfgHash              *Hash    `protobuf:"bytes,2,opt,name=cfg_hash,json=cfgHash,proto3" json:"cfg_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigReference) Reset()         { *m = ConfigReference{} }
func (m *ConfigReference) String() string { return proto.CompactTextString(m) }
func (*ConfigReference) ProtoMessage()    {}
func (*ConfigReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_60255c37bab97d9c, []int{1}
}
func (m *ConfigReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigReference.Unmarshal(m, b)
}
func (m *ConfigReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigReference.Marshal(b, m, deterministic)
}
func (dst *ConfigReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigReference.Merge(dst, src)
}
func (m *ConfigReference) XXX_Size() int {
	return xxx_messageInfo_ConfigReference.Size(m)
}
func (m *ConfigReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigReference.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigReference proto.InternalMessageInfo

func (m *ConfigReference) GetActualFrom() uint64 {
	if m != nil {
		return m.ActualFrom
	}
	return 0
}

func (m *ConfigReference) GetCfgHash() *Hash {
	if m != nil {
		return m.CfgHash
	}
	return nil
}

type TxLocation struct {
	BlockHeight          uint64   `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	PositionInBlock      uint64   `protobuf:"varint,2,opt,name=position_in_block,json=positionInBlock,proto3" json:"position_in_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxLocation) Reset()         { *m = TxLocation{} }
func (m *TxLocation) String() string { return proto.CompactTextString(m) }
func (*TxLocation) ProtoMessage()    {}
func (*TxLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_60255c37bab97d9c, []int{2}
}
func (m *TxLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxLocation.Unmarshal(m, b)
}
func (m *TxLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxLocation.Marshal(b, m, deterministic)
}
func (dst *TxLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxLocation.Merge(dst, src)
}
func (m *TxLocation) XXX_Size() int {
	return xxx_messageInfo_TxLocation.Size(m)
}
func (m *TxLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_TxLocation.DiscardUnknown(m)
}

var xxx_messageInfo_TxLocation proto.InternalMessageInfo

func (m *TxLocation) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *TxLocation) GetPositionInBlock() uint64 {
	if m != nil {
		return m.PositionInBlock
	}
	return 0
}

type TransactionResult struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionResult) Reset()         { *m = TransactionResult{} }
func (m *TransactionResult) String() string { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()    {}
func (*TransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_60255c37bab97d9c, []int{3}
}
func (m *TransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResult.Unmarshal(m, b)
}
func (m *TransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResult.Marshal(b, m, deterministic)
}
func (dst *TransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResult.Merge(dst, src)
}
func (m *TransactionResult) XXX_Size() int {
	return xxx_messageInfo_TransactionResult.Size(m)
}
func (m *TransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResult proto.InternalMessageInfo

func (m *TransactionResult) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TransactionResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Block)(nil), "exonum.Block")
	proto.RegisterType((*ConfigReference)(nil), "exonum.ConfigReference")
	proto.RegisterType((*TxLocation)(nil), "exonum.TxLocation")
	proto.RegisterType((*TransactionResult)(nil), "exonum.TransactionResult")
}

func init() { proto.RegisterFile("blockchain.proto", fileDescriptor_blockchain_60255c37bab97d9c) }

var fileDescriptor_blockchain_60255c37bab97d9c = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x0b, 0xd3, 0x30,
	0x14, 0xc7, 0xe9, 0xdc, 0xba, 0xed, 0x75, 0x63, 0x2e, 0x07, 0xa9, 0x5e, 0xac, 0x03, 0xb5, 0x2a,
	0x76, 0xa0, 0x7e, 0x82, 0x0d, 0x64, 0x03, 0xbd, 0x94, 0x9d, 0xf4, 0x50, 0xb2, 0x2c, 0x6d, 0x82,
	0x6d, 0x12, 0x92, 0x54, 0xea, 0x57, 0xf5, 0xd3, 0x48, 0x92, 0x0e, 0x3c, 0xec, 0xf6, 0xde, 0xff,
	0xfd, 0xfa, 0xa7, 0xef, 0xff, 0x02, 0x4f, 0xaf, 0xad, 0x24, 0xbf, 0x08, 0xc3, 0x5c, 0x14, 0x4a,
	0x4b, 0x2b, 0x51, 0x4c, 0x07, 0x29, 0xfa, 0xee, 0xc5, 0x9a, 0xd1, 0x56, 0x51, 0x6d, 0x82, 0xbc,
	0xfb, 0x1b, 0xc1, 0xec, 0xe0, 0x58, 0xf4, 0x12, 0x12, 0xa5, 0xa5, 0x92, 0x86, 0xea, 0x8a, 0xdf,
	0xd2, 0x28, 0x8b, 0xf2, 0x75, 0x09, 0x77, 0xe9, 0x7c, 0x43, 0xcf, 0x20, 0x66, 0x94, 0x37, 0xcc,
	0xa6, 0x93, 0x2c, 0xca, 0xa7, 0xe5, 0xd8, 0xa1, 0xe7, 0xb0, 0xb0, 0x43, 0x45, 0x64, 0x2f, 0x6c,
	0xfa, 0xc4, 0x7f, 0x35, 0xb7, 0xc3, 0xd1, 0xb5, 0xe8, 0x1d, 0x2c, 0x95, 0xa6, 0xbf, 0x2b, 0x86,
	0x0d, 0x4b, 0xa7, 0x59, 0x94, 0x27, 0x9f, 0x56, 0x45, 0xf8, 0x91, 0xe2, 0x84, 0x0d, 0x2b, 0x17,
	0x6e, 0xec, 0x2a, 0xf4, 0x1a, 0xe6, 0x76, 0x08, 0xe0, 0xec, 0x01, 0x18, 0xdb, 0xc1, 0x63, 0x1f,
	0x00, 0x8c, 0xc5, 0x96, 0x06, 0x32, 0x7e, 0x40, 0x2e, 0xfd, 0xdc, 0x95, 0xbb, 0x9f, 0xb0, 0x39,
	0x4a, 0x51, 0xf3, 0xa6, 0xa4, 0x35, 0xd5, 0x54, 0x10, 0xea, 0xb6, 0xc4, 0xc4, 0xf6, 0xb8, 0xad,
	0x6a, 0x2d, 0x3b, 0xbf, 0xe5, 0xb4, 0x84, 0x20, 0x7d, 0xd5, 0xb2, 0x43, 0x6f, 0x61, 0x41, 0xea,
	0x26, 0xd8, 0x4f, 0x1e, 0xd8, 0xcf, 0x49, 0xdd, 0x8c, 0xe6, 0x70, 0x19, 0xbe, 0x49, 0x82, 0x2d,
	0x97, 0x02, 0xbd, 0x82, 0x95, 0x8f, 0xbc, 0x1a, 0x23, 0x0a, 0xc6, 0x89, 0xd7, 0x4e, 0x21, 0xa7,
	0xf7, 0xb0, 0x55, 0xd2, 0x70, 0x87, 0x57, 0x5c, 0x54, 0x7e, 0x34, 0x46, 0xb9, 0xb9, 0x0f, 0xce,
	0xc2, 0x1f, 0x63, 0xf7, 0x1d, 0xb6, 0x17, 0x8d, 0x85, 0xc1, 0xc4, 0xa9, 0x25, 0x35, 0x7d, 0x6b,
	0xdd, 0x01, 0xdc, 0x6e, 0xbd, 0x19, 0x8f, 0x33, 0x76, 0x28, 0x83, 0xe4, 0x46, 0x0d, 0xd1, 0x5c,
	0x39, 0xd8, 0x5b, 0x2e, 0xcb, 0xff, 0xa5, 0x43, 0xfe, 0xe3, 0x4d, 0xc3, 0x2d, 0xeb, 0xaf, 0x05,
	0x91, 0xdd, 0x9e, 0x0b, 0xf1, 0xc5, 0x10, 0xee, 0xf2, 0xd8, 0x87, 0xd5, 0x3e, 0x36, 0x72, 0x6f,
	0xff, 0x28, 0x6a, 0xae, 0xb1, 0x7f, 0x16, 0x9f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xba, 0x0a,
	0xcf, 0x44, 0x41, 0x02, 0x00, 0x00,
}
