// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package types // import "github.com/inn4science/exonum-go/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Connect struct {
	PubAddr              string               `protobuf:"bytes,1,opt,name=pub_addr,json=pubAddr,proto3" json:"pub_addr,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	UserAgent            string               `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{0}
}
func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (dst *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(dst, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetPubAddr() string {
	if m != nil {
		return m.PubAddr
	}
	return ""
}

func (m *Connect) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Connect) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

type Status struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	LastHash             *Hash    `protobuf:"bytes,2,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{1}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Status) GetLastHash() *Hash {
	if m != nil {
		return m.LastHash
	}
	return nil
}

type Propose struct {
	Validator            uint32   `protobuf:"varint,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32   `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	PrevHash             *Hash    `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Transactions         []*Hash  `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Propose) Reset()         { *m = Propose{} }
func (m *Propose) String() string { return proto.CompactTextString(m) }
func (*Propose) ProtoMessage()    {}
func (*Propose) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{2}
}
func (m *Propose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Propose.Unmarshal(m, b)
}
func (m *Propose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Propose.Marshal(b, m, deterministic)
}
func (dst *Propose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Propose.Merge(dst, src)
}
func (m *Propose) XXX_Size() int {
	return xxx_messageInfo_Propose.Size(m)
}
func (m *Propose) XXX_DiscardUnknown() {
	xxx_messageInfo_Propose.DiscardUnknown(m)
}

var xxx_messageInfo_Propose proto.InternalMessageInfo

func (m *Propose) GetValidator() uint32 {
	if m != nil {
		return m.Validator
	}
	return 0
}

func (m *Propose) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Propose) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Propose) GetPrevHash() *Hash {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *Propose) GetTransactions() []*Hash {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Prevote struct {
	Validator            uint32   `protobuf:"varint,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32   `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	ProposeHash          *Hash    `protobuf:"bytes,4,opt,name=propose_hash,json=proposeHash,proto3" json:"propose_hash,omitempty"`
	LockedRound          uint32   `protobuf:"varint,5,opt,name=locked_round,json=lockedRound,proto3" json:"locked_round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prevote) Reset()         { *m = Prevote{} }
func (m *Prevote) String() string { return proto.CompactTextString(m) }
func (*Prevote) ProtoMessage()    {}
func (*Prevote) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{3}
}
func (m *Prevote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prevote.Unmarshal(m, b)
}
func (m *Prevote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prevote.Marshal(b, m, deterministic)
}
func (dst *Prevote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prevote.Merge(dst, src)
}
func (m *Prevote) XXX_Size() int {
	return xxx_messageInfo_Prevote.Size(m)
}
func (m *Prevote) XXX_DiscardUnknown() {
	xxx_messageInfo_Prevote.DiscardUnknown(m)
}

var xxx_messageInfo_Prevote proto.InternalMessageInfo

func (m *Prevote) GetValidator() uint32 {
	if m != nil {
		return m.Validator
	}
	return 0
}

func (m *Prevote) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Prevote) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Prevote) GetProposeHash() *Hash {
	if m != nil {
		return m.ProposeHash
	}
	return nil
}

func (m *Prevote) GetLockedRound() uint32 {
	if m != nil {
		return m.LockedRound
	}
	return 0
}

type Precommit struct {
	Validator            uint32               `protobuf:"varint,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Height               uint64               `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32               `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	ProposeHash          *Hash                `protobuf:"bytes,4,opt,name=propose_hash,json=proposeHash,proto3" json:"propose_hash,omitempty"`
	BlockHash            *Hash                `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Precommit) Reset()         { *m = Precommit{} }
func (m *Precommit) String() string { return proto.CompactTextString(m) }
func (*Precommit) ProtoMessage()    {}
func (*Precommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{4}
}
func (m *Precommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Precommit.Unmarshal(m, b)
}
func (m *Precommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Precommit.Marshal(b, m, deterministic)
}
func (dst *Precommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Precommit.Merge(dst, src)
}
func (m *Precommit) XXX_Size() int {
	return xxx_messageInfo_Precommit.Size(m)
}
func (m *Precommit) XXX_DiscardUnknown() {
	xxx_messageInfo_Precommit.DiscardUnknown(m)
}

var xxx_messageInfo_Precommit proto.InternalMessageInfo

func (m *Precommit) GetValidator() uint32 {
	if m != nil {
		return m.Validator
	}
	return 0
}

func (m *Precommit) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Precommit) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Precommit) GetProposeHash() *Hash {
	if m != nil {
		return m.ProposeHash
	}
	return nil
}

func (m *Precommit) GetBlockHash() *Hash {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Precommit) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type BlockResponse struct {
	To                   *PublicKey `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Block                *Block     `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Precommits           [][]byte   `protobuf:"bytes,3,rep,name=precommits,proto3" json:"precommits,omitempty"`
	Transactions         []*Hash    `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{5}
}
func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (dst *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(dst, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetTo() *PublicKey {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *BlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockResponse) GetPrecommits() [][]byte {
	if m != nil {
		return m.Precommits
	}
	return nil
}

func (m *BlockResponse) GetTransactions() []*Hash {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type TransactionsResponse struct {
	To                   *PublicKey `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Transactions         [][]byte   `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TransactionsResponse) Reset()         { *m = TransactionsResponse{} }
func (m *TransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionsResponse) ProtoMessage()    {}
func (*TransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{6}
}
func (m *TransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsResponse.Unmarshal(m, b)
}
func (m *TransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsResponse.Marshal(b, m, deterministic)
}
func (dst *TransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsResponse.Merge(dst, src)
}
func (m *TransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionsResponse.Size(m)
}
func (m *TransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsResponse proto.InternalMessageInfo

func (m *TransactionsResponse) GetTo() *PublicKey {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionsResponse) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ProposeRequest struct {
	To                   *PublicKey `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Height               uint64     `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ProposeHash          *Hash      `protobuf:"bytes,3,opt,name=propose_hash,json=proposeHash,proto3" json:"propose_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProposeRequest) Reset()         { *m = ProposeRequest{} }
func (m *ProposeRequest) String() string { return proto.CompactTextString(m) }
func (*ProposeRequest) ProtoMessage()    {}
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{7}
}
func (m *ProposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeRequest.Unmarshal(m, b)
}
func (m *ProposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeRequest.Marshal(b, m, deterministic)
}
func (dst *ProposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeRequest.Merge(dst, src)
}
func (m *ProposeRequest) XXX_Size() int {
	return xxx_messageInfo_ProposeRequest.Size(m)
}
func (m *ProposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeRequest proto.InternalMessageInfo

func (m *ProposeRequest) GetTo() *PublicKey {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ProposeRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProposeRequest) GetProposeHash() *Hash {
	if m != nil {
		return m.ProposeHash
	}
	return nil
}

type TransactionsRequest struct {
	To                   *PublicKey `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Txs                  []*Hash    `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TransactionsRequest) Reset()         { *m = TransactionsRequest{} }
func (m *TransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionsRequest) ProtoMessage()    {}
func (*TransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{8}
}
func (m *TransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsRequest.Unmarshal(m, b)
}
func (m *TransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsRequest.Marshal(b, m, deterministic)
}
func (dst *TransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsRequest.Merge(dst, src)
}
func (m *TransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionsRequest.Size(m)
}
func (m *TransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsRequest proto.InternalMessageInfo

func (m *TransactionsRequest) GetTo() *PublicKey {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionsRequest) GetTxs() []*Hash {
	if m != nil {
		return m.Txs
	}
	return nil
}

type PrevotesRequest struct {
	To                   *PublicKey `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Height               uint64     `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32     `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	ProposeHash          *Hash      `protobuf:"bytes,4,opt,name=propose_hash,json=proposeHash,proto3" json:"propose_hash,omitempty"`
	Validators           *BitVec    `protobuf:"bytes,5,opt,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PrevotesRequest) Reset()         { *m = PrevotesRequest{} }
func (m *PrevotesRequest) String() string { return proto.CompactTextString(m) }
func (*PrevotesRequest) ProtoMessage()    {}
func (*PrevotesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{9}
}
func (m *PrevotesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrevotesRequest.Unmarshal(m, b)
}
func (m *PrevotesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrevotesRequest.Marshal(b, m, deterministic)
}
func (dst *PrevotesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrevotesRequest.Merge(dst, src)
}
func (m *PrevotesRequest) XXX_Size() int {
	return xxx_messageInfo_PrevotesRequest.Size(m)
}
func (m *PrevotesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrevotesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrevotesRequest proto.InternalMessageInfo

func (m *PrevotesRequest) GetTo() *PublicKey {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *PrevotesRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PrevotesRequest) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *PrevotesRequest) GetProposeHash() *Hash {
	if m != nil {
		return m.ProposeHash
	}
	return nil
}

func (m *PrevotesRequest) GetValidators() *BitVec {
	if m != nil {
		return m.Validators
	}
	return nil
}

type PeersRequest struct {
	To                   *PublicKey `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PeersRequest) Reset()         { *m = PeersRequest{} }
func (m *PeersRequest) String() string { return proto.CompactTextString(m) }
func (*PeersRequest) ProtoMessage()    {}
func (*PeersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{10}
}
func (m *PeersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersRequest.Unmarshal(m, b)
}
func (m *PeersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersRequest.Marshal(b, m, deterministic)
}
func (dst *PeersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersRequest.Merge(dst, src)
}
func (m *PeersRequest) XXX_Size() int {
	return xxx_messageInfo_PeersRequest.Size(m)
}
func (m *PeersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersRequest proto.InternalMessageInfo

func (m *PeersRequest) GetTo() *PublicKey {
	if m != nil {
		return m.To
	}
	return nil
}

type BlockRequest struct {
	To                   *PublicKey `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Height               uint64     `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_00a0a22c4ac237ab, []int{11}
}
func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (dst *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(dst, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetTo() *PublicKey {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *BlockRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Connect)(nil), "exonum.Connect")
	proto.RegisterType((*Status)(nil), "exonum.Status")
	proto.RegisterType((*Propose)(nil), "exonum.Propose")
	proto.RegisterType((*Prevote)(nil), "exonum.Prevote")
	proto.RegisterType((*Precommit)(nil), "exonum.Precommit")
	proto.RegisterType((*BlockResponse)(nil), "exonum.BlockResponse")
	proto.RegisterType((*TransactionsResponse)(nil), "exonum.TransactionsResponse")
	proto.RegisterType((*ProposeRequest)(nil), "exonum.ProposeRequest")
	proto.RegisterType((*TransactionsRequest)(nil), "exonum.TransactionsRequest")
	proto.RegisterType((*PrevotesRequest)(nil), "exonum.PrevotesRequest")
	proto.RegisterType((*PeersRequest)(nil), "exonum.PeersRequest")
	proto.RegisterType((*BlockRequest)(nil), "exonum.BlockRequest")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_00a0a22c4ac237ab) }

var fileDescriptor_protocol_00a0a22c4ac237ab = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xed, 0x6a, 0xd4, 0x40,
	0x14, 0x65, 0x37, 0xbb, 0xdb, 0xe6, 0x6e, 0xb6, 0x6a, 0x2c, 0xb2, 0x16, 0xad, 0xdb, 0x08, 0xb2,
	0x22, 0x26, 0x5a, 0x7d, 0x81, 0xd6, 0x3f, 0x4a, 0xff, 0x2c, 0x63, 0x11, 0x11, 0x64, 0x99, 0x24,
	0xd7, 0x24, 0x98, 0xcc, 0xc4, 0xcc, 0xa4, 0xb4, 0xe0, 0x0b, 0xf9, 0xd7, 0x57, 0xf0, 0x59, 0x7c,
	0x0f, 0x99, 0x99, 0xa4, 0xee, 0xf6, 0x83, 0xb6, 0xb8, 0xe0, 0xbf, 0x99, 0x7b, 0x4f, 0xce, 0x3d,
	0x27, 0x73, 0x2e, 0x6c, 0x94, 0x15, 0x97, 0x3c, 0xe2, 0xb9, 0xaf, 0x0f, 0xee, 0x00, 0x8f, 0x39,
	0xab, 0x8b, 0xad, 0x51, 0x8a, 0x79, 0x89, 0x95, 0x30, 0xe5, 0xad, 0xdb, 0x61, 0xce, 0xa3, 0xaf,
	0x51, 0x4a, 0x33, 0xd6, 0x54, 0x1e, 0x25, 0x9c, 0x27, 0x39, 0x06, 0xfa, 0x16, 0xd6, 0x5f, 0x02,
	0x99, 0x15, 0x28, 0x24, 0x2d, 0x4a, 0x03, 0xf0, 0x04, 0xac, 0xbd, 0xe1, 0x8c, 0x61, 0x24, 0xdd,
	0xfb, 0xb0, 0x5e, 0xd6, 0xe1, 0x9c, 0xc6, 0x71, 0x35, 0xee, 0x4c, 0x3a, 0x53, 0x9b, 0xac, 0x95,
	0x75, 0xb8, 0x17, 0xc7, 0x95, 0xeb, 0x43, 0x4f, 0x7d, 0x38, 0xee, 0x4e, 0x3a, 0xd3, 0xe1, 0xee,
	0x96, 0x6f, 0x58, 0xfd, 0x96, 0xd5, 0x3f, 0x6c, 0x59, 0x89, 0xc6, 0xb9, 0x0f, 0x01, 0x6a, 0x81,
	0xd5, 0x9c, 0x26, 0xc8, 0xe4, 0xd8, 0xd2, 0x64, 0xb6, 0xaa, 0xec, 0xa9, 0x82, 0x77, 0x00, 0x83,
	0xf7, 0x92, 0xca, 0x5a, 0xb8, 0xf7, 0x60, 0x90, 0x62, 0x96, 0xa4, 0x52, 0x4f, 0xec, 0x91, 0xe6,
	0xe6, 0x3e, 0x05, 0x3b, 0xa7, 0x42, 0xce, 0x53, 0x2a, 0xd2, 0x66, 0xaa, 0xe3, 0x1b, 0xd3, 0xfe,
	0x5b, 0x2a, 0x52, 0xb2, 0xae, 0xda, 0xea, 0xe4, 0xfd, 0xec, 0xc0, 0xda, 0xac, 0xe2, 0x25, 0x17,
	0xe8, 0x3e, 0x00, 0xfb, 0x88, 0xe6, 0x59, 0x4c, 0x25, 0x37, 0x1e, 0x46, 0xe4, 0x6f, 0x61, 0x61,
	0x58, 0x77, 0x69, 0xd8, 0x26, 0xf4, 0x2b, 0x5e, 0xb3, 0x58, 0x0b, 0x1d, 0x11, 0x73, 0x51, 0x12,
	0xca, 0x0a, 0x8f, 0x8c, 0x84, 0xde, 0x45, 0x12, 0x54, 0x5b, 0x9d, 0xdc, 0x17, 0xe0, 0xc8, 0x8a,
	0x32, 0x41, 0x23, 0x99, 0x71, 0x26, 0xc6, 0xfd, 0x89, 0x75, 0x0e, 0xbd, 0x84, 0xf0, 0x7e, 0x68,
	0xd1, 0x78, 0xc4, 0xe5, 0x6a, 0x45, 0x07, 0xe0, 0x94, 0xe6, 0x5f, 0x5c, 0xae, 0x7b, 0xd8, 0x20,
	0xb4, 0xf4, 0x1d, 0x70, 0x54, 0x66, 0x30, 0x9e, 0x1b, 0xb6, 0xbe, 0x66, 0x1b, 0x9a, 0x1a, 0x51,
	0x25, 0xef, 0x77, 0x07, 0xec, 0x59, 0x85, 0x11, 0x2f, 0x8a, 0x4c, 0xfe, 0x5f, 0xb5, 0xcf, 0x00,
	0x74, 0xc4, 0x0d, 0xbc, 0x7f, 0x01, 0xdc, 0xd6, 0x7d, 0x0d, 0x6e, 0x43, 0x3b, 0xb8, 0x5e, 0x68,
	0xd5, 0x9b, 0x8c, 0xf6, 0xd5, 0xd7, 0x04, 0x45, 0xc9, 0x99, 0x40, 0x77, 0x07, 0xba, 0x92, 0x6b,
	0x93, 0xc3, 0xdd, 0x3b, 0xed, 0x98, 0x59, 0x1d, 0xe6, 0x59, 0x74, 0x80, 0x27, 0xa4, 0x2b, 0xb9,
	0xfb, 0x18, 0xfa, 0x7a, 0x62, 0x13, 0xd2, 0x51, 0x8b, 0x32, 0x44, 0xa6, 0xe7, 0x6e, 0x03, 0x94,
	0xed, 0x0f, 0x14, 0x63, 0x6b, 0x62, 0x4d, 0x1d, 0xb2, 0x50, 0x39, 0x97, 0x9f, 0xde, 0x95, 0xf9,
	0xf9, 0x0c, 0x9b, 0x87, 0x0b, 0xf7, 0x9b, 0x28, 0xf6, 0xce, 0x0c, 0xeb, 0x6a, 0x39, 0xcb, 0xf4,
	0xdf, 0x61, 0xa3, 0x59, 0x29, 0x82, 0xdf, 0x6a, 0x14, 0xf2, 0x3a, 0xc4, 0x97, 0xbd, 0xfd, 0xd9,
	0x57, 0xb6, 0xae, 0x78, 0x65, 0xef, 0x23, 0xdc, 0x5d, 0x36, 0x77, 0x6d, 0x09, 0xdb, 0x60, 0xc9,
	0x63, 0x63, 0xe9, 0xec, 0x04, 0xd5, 0xf0, 0x7e, 0x75, 0xe0, 0x56, 0xb3, 0x76, 0x62, 0x05, 0xce,
	0x56, 0x94, 0x6a, 0x1f, 0xe0, 0x74, 0x83, 0x44, 0x93, 0xea, 0x8d, 0xd3, 0x20, 0x65, 0xf2, 0x03,
	0x46, 0x64, 0x01, 0xe1, 0xbd, 0x04, 0x67, 0x86, 0x58, 0xdd, 0xc0, 0x81, 0xf7, 0x0e, 0x9c, 0x26,
	0xda, 0xff, 0x6a, 0x7a, 0x7f, 0xfa, 0xe9, 0x49, 0x92, 0xc9, 0xb4, 0x0e, 0xfd, 0x88, 0x17, 0x41,
	0xc6, 0xd8, 0x6b, 0x11, 0x65, 0xc8, 0x22, 0x0c, 0x0c, 0xcd, 0xf3, 0x84, 0x07, 0xf2, 0xa4, 0x44,
	0x11, 0x0e, 0xf4, 0xaa, 0xbd, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xa7, 0x00, 0xf0, 0xbe,
	0x06, 0x00, 0x00,
}
