// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package testTypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import types "github.com/inn4science/exonum-go/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VCGConfiguration struct {
	Version              uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SystemAccount        *types.PublicKey `protobuf:"bytes,2,opt,name=system_account,json=systemAccount,proto3" json:"system_account,omitempty"`
	Initialized          bool             `protobuf:"varint,3,opt,name=initialized,proto3" json:"initialized,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *VCGConfiguration) Reset()         { *m = VCGConfiguration{} }
func (m *VCGConfiguration) String() string { return proto.CompactTextString(m) }
func (*VCGConfiguration) ProtoMessage()    {}
func (*VCGConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{0}
}
func (m *VCGConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VCGConfiguration.Unmarshal(m, b)
}
func (m *VCGConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VCGConfiguration.Marshal(b, m, deterministic)
}
func (dst *VCGConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VCGConfiguration.Merge(dst, src)
}
func (m *VCGConfiguration) XXX_Size() int {
	return xxx_messageInfo_VCGConfiguration.Size(m)
}
func (m *VCGConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_VCGConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_VCGConfiguration proto.InternalMessageInfo

func (m *VCGConfiguration) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VCGConfiguration) GetSystemAccount() *types.PublicKey {
	if m != nil {
		return m.SystemAccount
	}
	return nil
}

func (m *VCGConfiguration) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

type AffiliateAccount struct {
	Version              uint32             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PublicKey            *types.PublicKey   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AffiliationType      AccountAffiliation `protobuf:"varint,3,opt,name=affiliation_type,json=affiliationType,proto3,enum=node.AccountAffiliation" json:"affiliation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AffiliateAccount) Reset()         { *m = AffiliateAccount{} }
func (m *AffiliateAccount) String() string { return proto.CompactTextString(m) }
func (*AffiliateAccount) ProtoMessage()    {}
func (*AffiliateAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{1}
}
func (m *AffiliateAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AffiliateAccount.Unmarshal(m, b)
}
func (m *AffiliateAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AffiliateAccount.Marshal(b, m, deterministic)
}
func (dst *AffiliateAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AffiliateAccount.Merge(dst, src)
}
func (m *AffiliateAccount) XXX_Size() int {
	return xxx_messageInfo_AffiliateAccount.Size(m)
}
func (m *AffiliateAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_AffiliateAccount.DiscardUnknown(m)
}

var xxx_messageInfo_AffiliateAccount proto.InternalMessageInfo

func (m *AffiliateAccount) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AffiliateAccount) GetPublicKey() *types.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AffiliateAccount) GetAffiliationType() AccountAffiliation {
	if m != nil {
		return m.AffiliationType
	}
	return AccountAffiliation_AccountAffiliationNull
}

type AccountSigner struct {
	Version              uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PublicKey            *types.PublicKey `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Policy               SignerPolicy     `protobuf:"varint,3,opt,name=policy,proto3,enum=node.SignerPolicy" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountSigner) Reset()         { *m = AccountSigner{} }
func (m *AccountSigner) String() string { return proto.CompactTextString(m) }
func (*AccountSigner) ProtoMessage()    {}
func (*AccountSigner) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{2}
}
func (m *AccountSigner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSigner.Unmarshal(m, b)
}
func (m *AccountSigner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSigner.Marshal(b, m, deterministic)
}
func (dst *AccountSigner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSigner.Merge(dst, src)
}
func (m *AccountSigner) XXX_Size() int {
	return xxx_messageInfo_AccountSigner.Size(m)
}
func (m *AccountSigner) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSigner.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSigner proto.InternalMessageInfo

func (m *AccountSigner) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AccountSigner) GetPublicKey() *types.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AccountSigner) GetPolicy() SignerPolicy {
	if m != nil {
		return m.Policy
	}
	return SignerPolicy_SignerPolicyNull
}

type Account struct {
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Length of the transactions history.
	HistoryLen uint64 `protobuf:"varint,2,opt,name=history_len,json=historyLen,proto3" json:"history_len,omitempty"`
	// `Hash` of the transactions history.
	HistoryHash          *types.Hash         `protobuf:"bytes,3,opt,name=history_hash,json=historyHash,proto3" json:"history_hash,omitempty"`
	AccountUid           *types.Hash         `protobuf:"bytes,4,opt,name=account_uid,json=accountUid,proto3" json:"account_uid,omitempty"`
	PublicKey            *types.PublicKey    `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AccountType          AccountType         `protobuf:"varint,6,opt,name=account_type,json=accountType,proto3,enum=node.AccountType" json:"account_type,omitempty"`
	State                AccountState        `protobuf:"varint,7,opt,name=state,proto3,enum=node.AccountState" json:"state,omitempty"`
	Affiliates           []*AffiliateAccount `protobuf:"bytes,8,rep,name=affiliates,proto3" json:"affiliates,omitempty"`
	Signers              []*AccountSigner    `protobuf:"bytes,9,rep,name=signers,proto3" json:"signers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{3}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Account) GetHistoryLen() uint64 {
	if m != nil {
		return m.HistoryLen
	}
	return 0
}

func (m *Account) GetHistoryHash() *types.Hash {
	if m != nil {
		return m.HistoryHash
	}
	return nil
}

func (m *Account) GetAccountUid() *types.Hash {
	if m != nil {
		return m.AccountUid
	}
	return nil
}

func (m *Account) GetPublicKey() *types.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Account) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_AccountTypeNull
}

func (m *Account) GetState() AccountState {
	if m != nil {
		return m.State
	}
	return AccountState_AccountStateNull
}

func (m *Account) GetAffiliates() []*AffiliateAccount {
	if m != nil {
		return m.Affiliates
	}
	return nil
}

func (m *Account) GetSigners() []*AccountSigner {
	if m != nil {
		return m.Signers
	}
	return nil
}

type Asset struct {
	Version              uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer               *types.PublicKey `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Policies             []AssetPolicy    `protobuf:"varint,4,rep,packed,name=policies,proto3,enum=node.AssetPolicy" json:"policies,omitempty"`
	Issued               uint64           `protobuf:"varint,5,opt,name=issued,proto3" json:"issued,omitempty"`
	InCirculation        uint64           `protobuf:"varint,6,opt,name=in_circulation,json=inCirculation,proto3" json:"in_circulation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{4}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (dst *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(dst, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Asset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Asset) GetIssuer() *types.PublicKey {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *Asset) GetPolicies() []AssetPolicy {
	if m != nil {
		return m.Policies
	}
	return nil
}

func (m *Asset) GetIssued() uint64 {
	if m != nil {
		return m.Issued
	}
	return 0
}

func (m *Asset) GetInCirculation() uint64 {
	if m != nil {
		return m.InCirculation
	}
	return 0
}

type AccountWallet struct {
	Version              uint32     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint32     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Address              string     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Asset                string     `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	WalletType           WalletType `protobuf:"varint,5,opt,name=wallet_type,json=walletType,proto3,enum=node.WalletType" json:"wallet_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountWallet) Reset()         { *m = AccountWallet{} }
func (m *AccountWallet) String() string { return proto.CompactTextString(m) }
func (*AccountWallet) ProtoMessage()    {}
func (*AccountWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{5}
}
func (m *AccountWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountWallet.Unmarshal(m, b)
}
func (m *AccountWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountWallet.Marshal(b, m, deterministic)
}
func (dst *AccountWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountWallet.Merge(dst, src)
}
func (m *AccountWallet) XXX_Size() int {
	return xxx_messageInfo_AccountWallet.Size(m)
}
func (m *AccountWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountWallet.DiscardUnknown(m)
}

var xxx_messageInfo_AccountWallet proto.InternalMessageInfo

func (m *AccountWallet) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AccountWallet) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AccountWallet) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountWallet) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *AccountWallet) GetWalletType() WalletType {
	if m != nil {
		return m.WalletType
	}
	return WalletType_WalletTypeNull
}

type AccountWallets struct {
	Version              uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	List                 []*AccountWallet `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountWallets) Reset()         { *m = AccountWallets{} }
func (m *AccountWallets) String() string { return proto.CompactTextString(m) }
func (*AccountWallets) ProtoMessage()    {}
func (*AccountWallets) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{6}
}
func (m *AccountWallets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountWallets.Unmarshal(m, b)
}
func (m *AccountWallets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountWallets.Marshal(b, m, deterministic)
}
func (dst *AccountWallets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountWallets.Merge(dst, src)
}
func (m *AccountWallets) XXX_Size() int {
	return xxx_messageInfo_AccountWallets.Size(m)
}
func (m *AccountWallets) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountWallets.DiscardUnknown(m)
}

var xxx_messageInfo_AccountWallets proto.InternalMessageInfo

func (m *AccountWallets) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AccountWallets) GetList() []*AccountWallet {
	if m != nil {
		return m.List
	}
	return nil
}

type Wallet struct {
	Version              uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint32           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Address              string           `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Asset                string           `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	AccountKey           *types.PublicKey `protobuf:"bytes,5,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WalletType           WalletType       `protobuf:"varint,6,opt,name=wallet_type,json=walletType,proto3,enum=node.WalletType" json:"wallet_type,omitempty"`
	Balance              uint64           `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	LockedBalance        uint64           `protobuf:"varint,8,opt,name=locked_balance,json=lockedBalance,proto3" json:"locked_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{7}
}
func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (dst *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(dst, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Wallet) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Wallet) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Wallet) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Wallet) GetAccountKey() *types.PublicKey {
	if m != nil {
		return m.AccountKey
	}
	return nil
}

func (m *Wallet) GetWalletType() WalletType {
	if m != nil {
		return m.WalletType
	}
	return WalletType_WalletTypeNull
}

func (m *Wallet) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Wallet) GetLockedBalance() uint64 {
	if m != nil {
		return m.LockedBalance
	}
	return 0
}

type Transfer struct {
	Version              uint32               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	From                 string               `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Asset                string               `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64               `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Tx                   *types.Hash          `protobuf:"bytes,7,opt,name=tx,proto3" json:"tx,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{8}
}
func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (dst *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(dst, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transfer) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transfer) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transfer) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Transfer) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transfer) GetTx() *types.Hash {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *Transfer) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type AssetPair struct {
	Version              uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Symbol               string           `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Base                 string           `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string           `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	Rate                 float32          `protobuf:"fixed32,5,opt,name=rate,proto3" json:"rate,omitempty"`
	Manager              *types.PublicKey `protobuf:"bytes,6,opt,name=manager,proto3" json:"manager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AssetPair) Reset()         { *m = AssetPair{} }
func (m *AssetPair) String() string { return proto.CompactTextString(m) }
func (*AssetPair) ProtoMessage()    {}
func (*AssetPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{9}
}
func (m *AssetPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetPair.Unmarshal(m, b)
}
func (m *AssetPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetPair.Marshal(b, m, deterministic)
}
func (dst *AssetPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetPair.Merge(dst, src)
}
func (m *AssetPair) XXX_Size() int {
	return xxx_messageInfo_AssetPair.Size(m)
}
func (m *AssetPair) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetPair.DiscardUnknown(m)
}

var xxx_messageInfo_AssetPair proto.InternalMessageInfo

func (m *AssetPair) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AssetPair) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *AssetPair) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *AssetPair) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *AssetPair) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *AssetPair) GetManager() *types.PublicKey {
	if m != nil {
		return m.Manager
	}
	return nil
}

type Rate struct {
	Version              uint32               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Pair                 string               `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Rate                 float32              `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rate) Reset()         { *m = Rate{} }
func (m *Rate) String() string { return proto.CompactTextString(m) }
func (*Rate) ProtoMessage()    {}
func (*Rate) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{10}
}
func (m *Rate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rate.Unmarshal(m, b)
}
func (m *Rate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rate.Marshal(b, m, deterministic)
}
func (dst *Rate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rate.Merge(dst, src)
}
func (m *Rate) XXX_Size() int {
	return xxx_messageInfo_Rate.Size(m)
}
func (m *Rate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rate.DiscardUnknown(m)
}

var xxx_messageInfo_Rate proto.InternalMessageInfo

func (m *Rate) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Rate) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Rate) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Rate) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type ExchangeOrder struct {
	Version              uint32               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Pair                 string               `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Rate                 float32              `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExchangeOrder) Reset()         { *m = ExchangeOrder{} }
func (m *ExchangeOrder) String() string { return proto.CompactTextString(m) }
func (*ExchangeOrder) ProtoMessage()    {}
func (*ExchangeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_d61f9ef8a3c8c863, []int{11}
}
func (m *ExchangeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeOrder.Unmarshal(m, b)
}
func (m *ExchangeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeOrder.Marshal(b, m, deterministic)
}
func (dst *ExchangeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeOrder.Merge(dst, src)
}
func (m *ExchangeOrder) XXX_Size() int {
	return xxx_messageInfo_ExchangeOrder.Size(m)
}
func (m *ExchangeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeOrder proto.InternalMessageInfo

func (m *ExchangeOrder) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ExchangeOrder) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *ExchangeOrder) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *ExchangeOrder) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*VCGConfiguration)(nil), "node.VCGConfiguration")
	proto.RegisterType((*AffiliateAccount)(nil), "node.AffiliateAccount")
	proto.RegisterType((*AccountSigner)(nil), "node.AccountSigner")
	proto.RegisterType((*Account)(nil), "node.Account")
	proto.RegisterType((*Asset)(nil), "node.Asset")
	proto.RegisterType((*AccountWallet)(nil), "node.AccountWallet")
	proto.RegisterType((*AccountWallets)(nil), "node.AccountWallets")
	proto.RegisterType((*Wallet)(nil), "node.Wallet")
	proto.RegisterType((*Transfer)(nil), "node.Transfer")
	proto.RegisterType((*AssetPair)(nil), "node.AssetPair")
	proto.RegisterType((*Rate)(nil), "node.Rate")
	proto.RegisterType((*ExchangeOrder)(nil), "node.ExchangeOrder")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_entity_d61f9ef8a3c8c863) }

var fileDescriptor_entity_d61f9ef8a3c8c863 = []byte{
	// 903 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5f, 0x8f, 0xdb, 0x44,
	0x10, 0x97, 0x13, 0xe7, 0xdf, 0xf8, 0x12, 0xae, 0x0b, 0x3a, 0x59, 0x15, 0x52, 0x23, 0x4b, 0x88,
	0x00, 0x3a, 0x87, 0xa6, 0x15, 0xea, 0xeb, 0xf5, 0x84, 0x40, 0x02, 0x89, 0x6a, 0x7b, 0x80, 0xc4,
	0x4b, 0xb4, 0xb1, 0x37, 0xc9, 0xaa, 0xf6, 0xae, 0xf1, 0xae, 0xdb, 0x33, 0x8f, 0xbc, 0x80, 0xe0,
	0x2b, 0xc0, 0x13, 0x2f, 0x7c, 0x1a, 0x3e, 0x13, 0xda, 0x7f, 0x97, 0xdc, 0x71, 0xcd, 0x81, 0x44,
	0xdf, 0x66, 0xd6, 0xbf, 0xdd, 0xf9, 0xcd, 0x6f, 0x66, 0x76, 0x0d, 0x47, 0x94, 0x2b, 0xa6, 0xda,
	0xb4, 0xaa, 0x85, 0x12, 0x28, 0xe4, 0x22, 0xa7, 0xf7, 0x23, 0xd5, 0x56, 0x54, 0xda, 0xa5, 0xfb,
	0xe3, 0x2d, 0x2d, 0x2a, 0x5a, 0x7b, 0xf7, 0xc1, 0x46, 0x88, 0x4d, 0x41, 0xe7, 0xc6, 0x5b, 0x35,
	0xeb, 0xb9, 0x62, 0x25, 0x95, 0x8a, 0x94, 0x95, 0x05, 0x24, 0x3f, 0x07, 0x70, 0xfc, 0xcd, 0xf9,
	0x67, 0xe7, 0x82, 0xaf, 0xd9, 0xa6, 0xa9, 0x89, 0x62, 0x82, 0xa3, 0x18, 0x06, 0x2f, 0x69, 0x2d,
	0x99, 0xe0, 0x71, 0x30, 0x0d, 0x66, 0x63, 0xec, 0x5d, 0xf4, 0x04, 0x26, 0xb2, 0x95, 0x8a, 0x96,
	0x4b, 0x92, 0x65, 0xa2, 0xe1, 0x2a, 0xee, 0x4c, 0x83, 0x59, 0xb4, 0xb8, 0x97, 0xd2, 0x4b, 0xc1,
	0x9b, 0x32, 0x7d, 0xd6, 0xac, 0x0a, 0x96, 0x7d, 0x41, 0x5b, 0x3c, 0xb6, 0xc0, 0x33, 0x8b, 0x43,
	0x53, 0x88, 0x18, 0x67, 0x8a, 0x91, 0x82, 0xfd, 0x40, 0xf3, 0xb8, 0x3b, 0x0d, 0x66, 0x43, 0xbc,
	0xbf, 0x94, 0xfc, 0x11, 0xc0, 0xf1, 0xd9, 0x7a, 0xcd, 0x0a, 0x46, 0x14, 0xf5, 0xdb, 0x5e, 0x4f,
	0xe5, 0x63, 0x80, 0xca, 0x04, 0x5b, 0xbe, 0xa0, 0xed, 0xeb, 0x69, 0x8c, 0x2a, 0x6f, 0xa2, 0x73,
	0x38, 0x26, 0xee, 0x7c, 0x26, 0xf8, 0x52, 0xcb, 0x66, 0x78, 0x4c, 0x16, 0x71, 0xaa, 0x95, 0x4c,
	0x5d, 0xd0, 0xb3, 0x1d, 0x08, 0xbf, 0xb5, 0xb7, 0xe3, 0xa2, 0xad, 0x68, 0xf2, 0x53, 0x00, 0x63,
	0x87, 0x7b, 0xce, 0x36, 0x9c, 0xd6, 0xff, 0x2b, 0xc5, 0x0f, 0xa1, 0x5f, 0x89, 0x82, 0x65, 0xad,
	0x23, 0x86, 0x2c, 0x31, 0x1b, 0xe9, 0x99, 0xf9, 0x82, 0x1d, 0x22, 0xf9, 0xbd, 0x0b, 0x83, 0xbb,
	0x65, 0x7a, 0x00, 0xd1, 0x96, 0x49, 0x25, 0xea, 0x76, 0x59, 0x50, 0x6e, 0x48, 0x84, 0x18, 0xdc,
	0xd2, 0x97, 0x94, 0xa3, 0x39, 0x1c, 0x79, 0xc0, 0x96, 0xc8, 0xad, 0x09, 0x1c, 0x2d, 0x8e, 0x3c,
	0xcd, 0xcf, 0x89, 0xdc, 0x62, 0x7f, 0x84, 0x76, 0xd0, 0x29, 0x44, 0xae, 0xf8, 0xcb, 0x86, 0xe5,
	0x71, 0x78, 0x0b, 0x1e, 0x1c, 0xe0, 0x6b, 0x96, 0xdf, 0x10, 0xa1, 0xf7, 0x2f, 0x44, 0x78, 0x0c,
	0x47, 0x3e, 0x80, 0xa9, 0x51, 0xdf, 0x48, 0x71, 0xef, 0x5a, 0x8d, 0x74, 0x2d, 0xb0, 0xe7, 0xa1,
	0x1d, 0x34, 0x83, 0x9e, 0x54, 0x44, 0xd1, 0x78, 0xb0, 0xaf, 0x9c, 0x2f, 0x95, 0xfe, 0x82, 0x2d,
	0x00, 0x7d, 0x02, 0xe0, 0xab, 0x4a, 0x65, 0x3c, 0x9c, 0x76, 0x67, 0xd1, 0xe2, 0xc4, 0xc1, 0x6f,
	0xf4, 0x1f, 0xde, 0x43, 0xa2, 0x53, 0x18, 0x48, 0x53, 0x08, 0x19, 0x8f, 0xcc, 0xa6, 0xb7, 0xaf,
	0xc7, 0x30, 0xdf, 0xb0, 0xc7, 0x24, 0x7f, 0x05, 0xd0, 0x3b, 0x93, 0x92, 0x1e, 0xaa, 0x0e, 0x82,
	0x90, 0x93, 0x92, 0x9a, 0xb2, 0x8c, 0xb0, 0xb1, 0xd1, 0x07, 0xd0, 0x67, 0x52, 0x36, 0xb4, 0x76,
	0xa5, 0xb8, 0x45, 0x2c, 0x07, 0x40, 0xa7, 0x30, 0x34, 0xcd, 0xc0, 0xa8, 0x8c, 0xc3, 0x69, 0x77,
	0x4f, 0x25, 0x1d, 0xd7, 0xf5, 0xcb, 0x15, 0x04, 0x9d, 0xb8, 0x93, 0x73, 0x53, 0x86, 0xd0, 0x1d,
	0x93, 0xa3, 0xf7, 0x60, 0xc2, 0xf8, 0x32, 0x63, 0x75, 0xd6, 0x14, 0xa6, 0xd3, 0x8d, 0xe4, 0x21,
	0x1e, 0x33, 0x7e, 0xbe, 0x5b, 0x4c, 0x7e, 0xdb, 0xb5, 0xfe, 0xb7, 0xa4, 0x28, 0x0e, 0x26, 0x36,
	0x81, 0x0e, 0xcb, 0x4d, 0x5a, 0x63, 0xdc, 0x61, 0xb9, 0x46, 0x92, 0x3c, 0xaf, 0xa9, 0x94, 0x26,
	0xab, 0x11, 0xf6, 0x2e, 0x7a, 0x07, 0x7a, 0x44, 0xb3, 0x35, 0x8d, 0x34, 0xc2, 0xd6, 0x41, 0x0f,
	0x21, 0x7a, 0x65, 0x62, 0xd8, 0x16, 0xe8, 0x99, 0x9a, 0x1e, 0xdb, 0xe4, 0x6c, 0x70, 0xd3, 0x01,
	0xf0, 0xea, 0xca, 0x4e, 0x9e, 0xc3, 0xe4, 0x1a, 0x3b, 0x79, 0x80, 0xde, 0xfb, 0x10, 0x16, 0x4c,
	0xea, 0xdb, 0xeb, 0x9f, 0x75, 0xb4, 0xbb, 0xb1, 0x01, 0x24, 0xbf, 0x74, 0xa0, 0xff, 0xc6, 0x93,
	0x5d, 0xec, 0x26, 0xea, 0xe0, 0x8c, 0xf8, 0xb1, 0xd2, 0x43, 0x72, 0x43, 0xa0, 0xfe, 0xdd, 0x02,
	0x69, 0x5a, 0x2b, 0x52, 0x10, 0x9e, 0xd9, 0x19, 0x09, 0xb1, 0x77, 0x75, 0x03, 0x14, 0x22, 0x7b,
	0x41, 0xf3, 0xa5, 0x07, 0x0c, 0x6d, 0x03, 0xd8, 0xd5, 0xa7, 0x76, 0x51, 0x77, 0xf4, 0xf0, 0xa2,
	0x26, 0x5c, 0xae, 0x0f, 0x5e, 0x7b, 0x08, 0xc2, 0x75, 0x2d, 0x4a, 0x97, 0xbb, 0xb1, 0xb5, 0x44,
	0x4a, 0xb8, 0xac, 0x3b, 0x4a, 0xec, 0x84, 0xe8, 0xed, 0x0b, 0x71, 0x02, 0x7d, 0x52, 0x9a, 0x67,
	0xc5, 0x36, 0xa0, 0xf3, 0xd0, 0xbb, 0xd0, 0x51, 0x97, 0x86, 0xf4, 0xcd, 0x9b, 0xa6, 0xa3, 0x2e,
	0xd1, 0x13, 0x18, 0x5d, 0x3d, 0x6b, 0x86, 0x78, 0xb4, 0xb8, 0x9f, 0xda, 0x87, 0x2f, 0xf5, 0x0f,
	0x5f, 0x7a, 0xe1, 0x11, 0x78, 0x07, 0x4e, 0xfe, 0x0c, 0x60, 0x64, 0x47, 0x85, 0xb0, 0x43, 0x19,
	0x9d, 0x40, 0x5f, 0xb6, 0xe5, 0x4a, 0x14, 0x6e, 0x50, 0x9d, 0xa7, 0x33, 0x5d, 0x11, 0x49, 0x7d,
	0xa6, 0xda, 0xd6, 0x99, 0x7d, 0xdf, 0x08, 0x45, 0x7d, 0x89, 0x8d, 0xa3, 0x91, 0xb5, 0xbe, 0x9c,
	0x74, 0xba, 0x1d, 0x6c, 0x6c, 0xf4, 0x11, 0x0c, 0x4a, 0xc2, 0xc9, 0x86, 0xd6, 0x26, 0xdd, 0x5b,
	0x4b, 0xee, 0x11, 0xc9, 0x8f, 0x01, 0x84, 0x58, 0xef, 0x3a, 0xa8, 0x7b, 0x45, 0x58, 0xed, 0x2f,
	0x13, 0x6d, 0x5f, 0xc5, 0xed, 0xee, 0xc5, 0xbd, 0xa6, 0x57, 0xf8, 0x5f, 0xf4, 0xfa, 0x35, 0x80,
	0xf1, 0xa7, 0x97, 0xd9, 0x96, 0xf0, 0x0d, 0xfd, 0xaa, 0xce, 0xef, 0xea, 0x82, 0x37, 0xcb, 0xe6,
	0xe9, 0xa3, 0xef, 0x1e, 0x6e, 0x98, 0x2a, 0xc8, 0x2a, 0x65, 0x9c, 0x3f, 0x96, 0x19, 0xa3, 0x3c,
	0xa3, 0x69, 0x26, 0xca, 0xf9, 0xcb, 0x6c, 0x33, 0xd7, 0x93, 0x70, 0x9a, 0x15, 0x8c, 0x72, 0x65,
	0xec, 0xb9, 0xf9, 0x4d, 0x5a, 0xf5, 0xcd, 0x99, 0x8f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd0,
	0xc4, 0xbe, 0xb5, 0x4a, 0x09, 0x00, 0x00,
}
