// Code generated by protoc-gen-go. DO NOT EDIT.
// source: txs.proto

package testTypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import types "github.com/inn4science/exonum-go/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_TransactionTypeNull   TransactionType = 0
	TransactionType_TxCreateAccount       TransactionType = 1
	TransactionType_TxSetAccountPublicKey TransactionType = 2
	TransactionType_TxSetAffiliate        TransactionType = 3
	TransactionType_TxSetSigner           TransactionType = 4
	TransactionType_TxCreateAsset         TransactionType = 5
	TransactionType_TxCreateWallet        TransactionType = 6
	TransactionType_TxIssue               TransactionType = 7
	TransactionType_TxWithdraw            TransactionType = 8
	TransactionType_TxSystemTransfer      TransactionType = 9
	TransactionType_TxPayment             TransactionType = 10
	TransactionType_TxCreateAssetPair     TransactionType = 11
	TransactionType_TxSetRate             TransactionType = 12
	TransactionType_TxManageExchangeOrder TransactionType = 13
)

var TransactionType_name = map[int32]string{
	0:  "TransactionTypeNull",
	1:  "TxCreateAccount",
	2:  "TxSetAccountPublicKey",
	3:  "TxSetAffiliate",
	4:  "TxSetSigner",
	5:  "TxCreateAsset",
	6:  "TxCreateWallet",
	7:  "TxIssue",
	8:  "TxWithdraw",
	9:  "TxSystemTransfer",
	10: "TxPayment",
	11: "TxCreateAssetPair",
	12: "TxSetRate",
	13: "TxManageExchangeOrder",
}
var TransactionType_value = map[string]int32{
	"TransactionTypeNull":   0,
	"TxCreateAccount":       1,
	"TxSetAccountPublicKey": 2,
	"TxSetAffiliate":        3,
	"TxSetSigner":           4,
	"TxCreateAsset":         5,
	"TxCreateWallet":        6,
	"TxIssue":               7,
	"TxWithdraw":            8,
	"TxSystemTransfer":      9,
	"TxPayment":             10,
	"TxCreateAssetPair":     11,
	"TxSetRate":             12,
	"TxManageExchangeOrder": 13,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{0}
}

type TxMeta struct {
	TxType               TransactionType `protobuf:"varint,1,opt,name=tx_type,json=txType,proto3,enum=node.TransactionType" json:"tx_type,omitempty"`
	ProtocolVer          uint32          `protobuf:"varint,2,opt,name=protocol_ver,json=protocolVer,proto3" json:"protocol_ver,omitempty"`
	TxVer                uint32          `protobuf:"varint,3,opt,name=tx_ver,json=txVer,proto3" json:"tx_ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TxMeta) Reset()         { *m = TxMeta{} }
func (m *TxMeta) String() string { return proto.CompactTextString(m) }
func (*TxMeta) ProtoMessage()    {}
func (*TxMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{0}
}
func (m *TxMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxMeta.Unmarshal(m, b)
}
func (m *TxMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxMeta.Marshal(b, m, deterministic)
}
func (dst *TxMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxMeta.Merge(dst, src)
}
func (m *TxMeta) XXX_Size() int {
	return xxx_messageInfo_TxMeta.Size(m)
}
func (m *TxMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TxMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TxMeta proto.InternalMessageInfo

func (m *TxMeta) GetTxType() TransactionType {
	if m != nil {
		return m.TxType
	}
	return TransactionType_TransactionTypeNull
}

func (m *TxMeta) GetProtocolVer() uint32 {
	if m != nil {
		return m.ProtocolVer
	}
	return 0
}

func (m *TxMeta) GetTxVer() uint32 {
	if m != nil {
		return m.TxVer
	}
	return 0
}

type NullTx struct {
	Meta                 *TxMeta  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullTx) Reset()         { *m = NullTx{} }
func (m *NullTx) String() string { return proto.CompactTextString(m) }
func (*NullTx) ProtoMessage()    {}
func (*NullTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{1}
}
func (m *NullTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullTx.Unmarshal(m, b)
}
func (m *NullTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullTx.Marshal(b, m, deterministic)
}
func (dst *NullTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullTx.Merge(dst, src)
}
func (m *NullTx) XXX_Size() int {
	return xxx_messageInfo_NullTx.Size(m)
}
func (m *NullTx) XXX_DiscardUnknown() {
	xxx_messageInfo_NullTx.DiscardUnknown(m)
}

var xxx_messageInfo_NullTx proto.InternalMessageInfo

func (m *NullTx) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type CreateAccount struct {
	Meta                 *TxMeta     `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	AccountUid           *types.Hash `protobuf:"bytes,2,opt,name=account_uid,json=accountUid,proto3" json:"account_uid,omitempty"`
	AccountType          AccountType `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=node.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAccount) Reset()         { *m = CreateAccount{} }
func (m *CreateAccount) String() string { return proto.CompactTextString(m) }
func (*CreateAccount) ProtoMessage()    {}
func (*CreateAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{2}
}
func (m *CreateAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccount.Unmarshal(m, b)
}
func (m *CreateAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccount.Marshal(b, m, deterministic)
}
func (dst *CreateAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccount.Merge(dst, src)
}
func (m *CreateAccount) XXX_Size() int {
	return xxx_messageInfo_CreateAccount.Size(m)
}
func (m *CreateAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccount proto.InternalMessageInfo

func (m *CreateAccount) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *CreateAccount) GetAccountUid() *types.Hash {
	if m != nil {
		return m.AccountUid
	}
	return nil
}

func (m *CreateAccount) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_AccountTypeNull
}

type SetAccountPublicKey struct {
	Meta                 *TxMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	AccountUid           *types.Hash      `protobuf:"bytes,2,opt,name=account_uid,json=accountUid,proto3" json:"account_uid,omitempty"`
	PublicKey            *types.PublicKey `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SetAccountPublicKey) Reset()         { *m = SetAccountPublicKey{} }
func (m *SetAccountPublicKey) String() string { return proto.CompactTextString(m) }
func (*SetAccountPublicKey) ProtoMessage()    {}
func (*SetAccountPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{3}
}
func (m *SetAccountPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAccountPublicKey.Unmarshal(m, b)
}
func (m *SetAccountPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAccountPublicKey.Marshal(b, m, deterministic)
}
func (dst *SetAccountPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAccountPublicKey.Merge(dst, src)
}
func (m *SetAccountPublicKey) XXX_Size() int {
	return xxx_messageInfo_SetAccountPublicKey.Size(m)
}
func (m *SetAccountPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAccountPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_SetAccountPublicKey proto.InternalMessageInfo

func (m *SetAccountPublicKey) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SetAccountPublicKey) GetAccountUid() *types.Hash {
	if m != nil {
		return m.AccountUid
	}
	return nil
}

func (m *SetAccountPublicKey) GetPublicKey() *types.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type SetSigner struct {
	Meta                 *TxMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Account              *types.PublicKey `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Signer               *types.PublicKey `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	Policy               SignerPolicy     `protobuf:"varint,4,opt,name=policy,proto3,enum=node.SignerPolicy" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SetSigner) Reset()         { *m = SetSigner{} }
func (m *SetSigner) String() string { return proto.CompactTextString(m) }
func (*SetSigner) ProtoMessage()    {}
func (*SetSigner) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{4}
}
func (m *SetSigner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSigner.Unmarshal(m, b)
}
func (m *SetSigner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSigner.Marshal(b, m, deterministic)
}
func (dst *SetSigner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSigner.Merge(dst, src)
}
func (m *SetSigner) XXX_Size() int {
	return xxx_messageInfo_SetSigner.Size(m)
}
func (m *SetSigner) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSigner.DiscardUnknown(m)
}

var xxx_messageInfo_SetSigner proto.InternalMessageInfo

func (m *SetSigner) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SetSigner) GetAccount() *types.PublicKey {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SetSigner) GetSigner() *types.PublicKey {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *SetSigner) GetPolicy() SignerPolicy {
	if m != nil {
		return m.Policy
	}
	return SignerPolicy_SignerPolicyNull
}

type SetAffiliate struct {
	Meta                 *TxMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Account              *types.PublicKey   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Affiliate            *types.PublicKey   `protobuf:"bytes,3,opt,name=affiliate,proto3" json:"affiliate,omitempty"`
	Relation             AccountAffiliation `protobuf:"varint,4,opt,name=relation,proto3,enum=node.AccountAffiliation" json:"relation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SetAffiliate) Reset()         { *m = SetAffiliate{} }
func (m *SetAffiliate) String() string { return proto.CompactTextString(m) }
func (*SetAffiliate) ProtoMessage()    {}
func (*SetAffiliate) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{5}
}
func (m *SetAffiliate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAffiliate.Unmarshal(m, b)
}
func (m *SetAffiliate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAffiliate.Marshal(b, m, deterministic)
}
func (dst *SetAffiliate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAffiliate.Merge(dst, src)
}
func (m *SetAffiliate) XXX_Size() int {
	return xxx_messageInfo_SetAffiliate.Size(m)
}
func (m *SetAffiliate) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAffiliate.DiscardUnknown(m)
}

var xxx_messageInfo_SetAffiliate proto.InternalMessageInfo

func (m *SetAffiliate) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SetAffiliate) GetAccount() *types.PublicKey {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SetAffiliate) GetAffiliate() *types.PublicKey {
	if m != nil {
		return m.Affiliate
	}
	return nil
}

func (m *SetAffiliate) GetRelation() AccountAffiliation {
	if m != nil {
		return m.Relation
	}
	return AccountAffiliation_AccountAffiliationNull
}

type CreateWallet struct {
	Meta                 *TxMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Asset                string           `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	AccountKey           *types.PublicKey `protobuf:"bytes,3,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WalletType           WalletType       `protobuf:"varint,4,opt,name=wallet_type,json=walletType,proto3,enum=node.WalletType" json:"wallet_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateWallet) Reset()         { *m = CreateWallet{} }
func (m *CreateWallet) String() string { return proto.CompactTextString(m) }
func (*CreateWallet) ProtoMessage()    {}
func (*CreateWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{6}
}
func (m *CreateWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWallet.Unmarshal(m, b)
}
func (m *CreateWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWallet.Marshal(b, m, deterministic)
}
func (dst *CreateWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWallet.Merge(dst, src)
}
func (m *CreateWallet) XXX_Size() int {
	return xxx_messageInfo_CreateWallet.Size(m)
}
func (m *CreateWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWallet.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWallet proto.InternalMessageInfo

func (m *CreateWallet) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *CreateWallet) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *CreateWallet) GetAccountKey() *types.PublicKey {
	if m != nil {
		return m.AccountKey
	}
	return nil
}

func (m *CreateWallet) GetWalletType() WalletType {
	if m != nil {
		return m.WalletType
	}
	return WalletType_WalletTypeNull
}

type CreateAsset struct {
	Meta                 *TxMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer               *types.PublicKey `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Policy               []AssetPolicy    `protobuf:"varint,4,rep,packed,name=policy,proto3,enum=node.AssetPolicy" json:"policy,omitempty"`
	InitialAmount        uint64           `protobuf:"varint,5,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateAsset) Reset()         { *m = CreateAsset{} }
func (m *CreateAsset) String() string { return proto.CompactTextString(m) }
func (*CreateAsset) ProtoMessage()    {}
func (*CreateAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{7}
}
func (m *CreateAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAsset.Unmarshal(m, b)
}
func (m *CreateAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAsset.Marshal(b, m, deterministic)
}
func (dst *CreateAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAsset.Merge(dst, src)
}
func (m *CreateAsset) XXX_Size() int {
	return xxx_messageInfo_CreateAsset.Size(m)
}
func (m *CreateAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAsset.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAsset proto.InternalMessageInfo

func (m *CreateAsset) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *CreateAsset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAsset) GetIssuer() *types.PublicKey {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *CreateAsset) GetPolicy() []AssetPolicy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *CreateAsset) GetInitialAmount() uint64 {
	if m != nil {
		return m.InitialAmount
	}
	return 0
}

type Issue struct {
	Meta                 *TxMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Asset                string               `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64               `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reference            string               `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
	Nonce                uint64               `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Issue) Reset()         { *m = Issue{} }
func (m *Issue) String() string { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()    {}
func (*Issue) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{8}
}
func (m *Issue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issue.Unmarshal(m, b)
}
func (m *Issue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issue.Marshal(b, m, deterministic)
}
func (dst *Issue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issue.Merge(dst, src)
}
func (m *Issue) XXX_Size() int {
	return xxx_messageInfo_Issue.Size(m)
}
func (m *Issue) XXX_DiscardUnknown() {
	xxx_messageInfo_Issue.DiscardUnknown(m)
}

var xxx_messageInfo_Issue proto.InternalMessageInfo

func (m *Issue) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Issue) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Issue) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Issue) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Issue) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Issue) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Withdraw struct {
	Meta                 *TxMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Address              string               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Asset                string               `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64               `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Reference            string               `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	Nonce                uint64               `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Withdraw) Reset()         { *m = Withdraw{} }
func (m *Withdraw) String() string { return proto.CompactTextString(m) }
func (*Withdraw) ProtoMessage()    {}
func (*Withdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{9}
}
func (m *Withdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Withdraw.Unmarshal(m, b)
}
func (m *Withdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Withdraw.Marshal(b, m, deterministic)
}
func (dst *Withdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdraw.Merge(dst, src)
}
func (m *Withdraw) XXX_Size() int {
	return xxx_messageInfo_Withdraw.Size(m)
}
func (m *Withdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdraw.DiscardUnknown(m)
}

var xxx_messageInfo_Withdraw proto.InternalMessageInfo

func (m *Withdraw) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Withdraw) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Withdraw) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Withdraw) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Withdraw) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Withdraw) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Withdraw) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type SystemTransfer struct {
	Meta                 *TxMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	From                 string               `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Asset                string               `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64               `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Reference            string               `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	Nonce                uint64               `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SystemTransfer) Reset()         { *m = SystemTransfer{} }
func (m *SystemTransfer) String() string { return proto.CompactTextString(m) }
func (*SystemTransfer) ProtoMessage()    {}
func (*SystemTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{10}
}
func (m *SystemTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemTransfer.Unmarshal(m, b)
}
func (m *SystemTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemTransfer.Marshal(b, m, deterministic)
}
func (dst *SystemTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemTransfer.Merge(dst, src)
}
func (m *SystemTransfer) XXX_Size() int {
	return xxx_messageInfo_SystemTransfer.Size(m)
}
func (m *SystemTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_SystemTransfer proto.InternalMessageInfo

func (m *SystemTransfer) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SystemTransfer) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SystemTransfer) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SystemTransfer) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *SystemTransfer) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SystemTransfer) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *SystemTransfer) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *SystemTransfer) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Payment struct {
	Meta                 *TxMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	From                 string               `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Asset                string               `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               uint64               `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  uint64               `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Reference            string               `protobuf:"bytes,7,opt,name=reference,proto3" json:"reference,omitempty"`
	Nonce                uint64               `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{11}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (dst *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(dst, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Payment) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Payment) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Payment) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Payment) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Payment) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Payment) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Payment) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type CreateAssetPair struct {
	Meta                 *TxMeta         `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	TxType               TransactionType `protobuf:"varint,2,opt,name=tx_type,json=txType,proto3,enum=node.TransactionType" json:"tx_type,omitempty"`
	Base                 string          `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string          `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	BaseRate             float32         `protobuf:"fixed32,5,opt,name=base_rate,json=baseRate,proto3" json:"base_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateAssetPair) Reset()         { *m = CreateAssetPair{} }
func (m *CreateAssetPair) String() string { return proto.CompactTextString(m) }
func (*CreateAssetPair) ProtoMessage()    {}
func (*CreateAssetPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{12}
}
func (m *CreateAssetPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssetPair.Unmarshal(m, b)
}
func (m *CreateAssetPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssetPair.Marshal(b, m, deterministic)
}
func (dst *CreateAssetPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssetPair.Merge(dst, src)
}
func (m *CreateAssetPair) XXX_Size() int {
	return xxx_messageInfo_CreateAssetPair.Size(m)
}
func (m *CreateAssetPair) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssetPair.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssetPair proto.InternalMessageInfo

func (m *CreateAssetPair) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *CreateAssetPair) GetTxType() TransactionType {
	if m != nil {
		return m.TxType
	}
	return TransactionType_TransactionTypeNull
}

func (m *CreateAssetPair) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *CreateAssetPair) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *CreateAssetPair) GetBaseRate() float32 {
	if m != nil {
		return m.BaseRate
	}
	return 0
}

type SetRate struct {
	Meta                 *TxMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Pair                 string               `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Rate                 float32              `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetRate) Reset()         { *m = SetRate{} }
func (m *SetRate) String() string { return proto.CompactTextString(m) }
func (*SetRate) ProtoMessage()    {}
func (*SetRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{13}
}
func (m *SetRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRate.Unmarshal(m, b)
}
func (m *SetRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRate.Marshal(b, m, deterministic)
}
func (dst *SetRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRate.Merge(dst, src)
}
func (m *SetRate) XXX_Size() int {
	return xxx_messageInfo_SetRate.Size(m)
}
func (m *SetRate) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRate.DiscardUnknown(m)
}

var xxx_messageInfo_SetRate proto.InternalMessageInfo

func (m *SetRate) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SetRate) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *SetRate) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *SetRate) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type ManageExchangeOrder struct {
	Meta                 *TxMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Wallet               string               `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Pair                 string               `protobuf:"bytes,4,opt,name=pair,proto3" json:"pair,omitempty"`
	Amount               uint64               `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Rate                 float32              `protobuf:"fixed32,6,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ManageExchangeOrder) Reset()         { *m = ManageExchangeOrder{} }
func (m *ManageExchangeOrder) String() string { return proto.CompactTextString(m) }
func (*ManageExchangeOrder) ProtoMessage()    {}
func (*ManageExchangeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_txs_bdd3bb7464a68248, []int{14}
}
func (m *ManageExchangeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManageExchangeOrder.Unmarshal(m, b)
}
func (m *ManageExchangeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManageExchangeOrder.Marshal(b, m, deterministic)
}
func (dst *ManageExchangeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManageExchangeOrder.Merge(dst, src)
}
func (m *ManageExchangeOrder) XXX_Size() int {
	return xxx_messageInfo_ManageExchangeOrder.Size(m)
}
func (m *ManageExchangeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ManageExchangeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ManageExchangeOrder proto.InternalMessageInfo

func (m *ManageExchangeOrder) GetMeta() *TxMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ManageExchangeOrder) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *ManageExchangeOrder) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *ManageExchangeOrder) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ManageExchangeOrder) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *ManageExchangeOrder) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*TxMeta)(nil), "node.TxMeta")
	proto.RegisterType((*NullTx)(nil), "node.NullTx")
	proto.RegisterType((*CreateAccount)(nil), "node.CreateAccount")
	proto.RegisterType((*SetAccountPublicKey)(nil), "node.SetAccountPublicKey")
	proto.RegisterType((*SetSigner)(nil), "node.SetSigner")
	proto.RegisterType((*SetAffiliate)(nil), "node.SetAffiliate")
	proto.RegisterType((*CreateWallet)(nil), "node.CreateWallet")
	proto.RegisterType((*CreateAsset)(nil), "node.CreateAsset")
	proto.RegisterType((*Issue)(nil), "node.Issue")
	proto.RegisterType((*Withdraw)(nil), "node.Withdraw")
	proto.RegisterType((*SystemTransfer)(nil), "node.SystemTransfer")
	proto.RegisterType((*Payment)(nil), "node.Payment")
	proto.RegisterType((*CreateAssetPair)(nil), "node.CreateAssetPair")
	proto.RegisterType((*SetRate)(nil), "node.SetRate")
	proto.RegisterType((*ManageExchangeOrder)(nil), "node.ManageExchangeOrder")
	proto.RegisterEnum("node.TransactionType", TransactionType_name, TransactionType_value)
}

func init() { proto.RegisterFile("txs.proto", fileDescriptor_txs_bdd3bb7464a68248) }

var fileDescriptor_txs_bdd3bb7464a68248 = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0xc6, 0x89, 0x63, 0xc7, 0xe5, 0x24, 0xe3, 0xe9, 0xd9, 0x59, 0xc2, 0x80, 0xc4, 0x60, 0x09,
	0x69, 0x18, 0xb4, 0x0e, 0x3b, 0x3b, 0x07, 0xae, 0x0b, 0x42, 0x02, 0xa1, 0x85, 0x91, 0xc7, 0xec,
	0x4a, 0x5c, 0xa2, 0x8e, 0xd3, 0xc9, 0xb4, 0xf0, 0x4f, 0xb0, 0x3b, 0x3b, 0xce, 0x43, 0x70, 0x45,
	0xbc, 0x02, 0x48, 0x1c, 0x78, 0x03, 0x0e, 0x70, 0xe0, 0x35, 0x78, 0x04, 0xee, 0x48, 0xa8, 0xff,
	0xf2, 0xb3, 0x8a, 0x67, 0x13, 0xb4, 0xd2, 0x9e, 0xdc, 0x55, 0x5d, 0xae, 0xfa, 0xbe, 0xea, 0xaf,
	0x7f, 0xc0, 0x61, 0x55, 0x19, 0xcc, 0x8a, 0x9c, 0xe5, 0xc8, 0xcc, 0xf2, 0x31, 0x39, 0xe9, 0xde,
	0x90, 0x64, 0x46, 0x0a, 0xe5, 0x3c, 0x71, 0xd9, 0x62, 0x46, 0xb4, 0xf1, 0xee, 0x34, 0xcf, 0xa7,
	0x09, 0x19, 0x08, 0x6b, 0x34, 0x9f, 0x0c, 0x18, 0x4d, 0x49, 0xc9, 0x70, 0x3a, 0x93, 0x01, 0x7e,
	0x01, 0x56, 0x54, 0x3d, 0x21, 0x0c, 0xa3, 0x00, 0x6c, 0x56, 0x0d, 0xf9, 0xcf, 0x7d, 0xe3, 0xd4,
	0x38, 0xeb, 0x5d, 0x1c, 0x07, 0x3c, 0x7d, 0x10, 0x15, 0x38, 0x2b, 0x71, 0xcc, 0x68, 0x9e, 0x45,
	0x8b, 0x19, 0x09, 0x2d, 0x56, 0xf1, 0x2f, 0x7a, 0x0f, 0x3a, 0x22, 0x45, 0x9c, 0x27, 0xc3, 0xe7,
	0xa4, 0xe8, 0x37, 0x4e, 0x8d, 0xb3, 0x6e, 0xe8, 0x6a, 0xdf, 0x53, 0x52, 0xa0, 0x63, 0xb0, 0x58,
	0x25, 0x26, 0x9b, 0x62, 0xb2, 0xc5, 0xaa, 0xa7, 0xa4, 0xf0, 0xcf, 0xc1, 0xfa, 0x6a, 0x9e, 0x24,
	0x51, 0x85, 0x4e, 0xc1, 0x4c, 0x09, 0xc3, 0xa2, 0xa0, 0x7b, 0xd1, 0x51, 0x05, 0x05, 0x9e, 0x50,
	0xcc, 0xf8, 0x3f, 0x1a, 0xd0, 0xfd, 0xb4, 0x20, 0x98, 0x91, 0xc7, 0x71, 0x9c, 0xcf, 0x33, 0xf6,
	0xf2, 0x7f, 0xd0, 0x03, 0x70, 0xb1, 0x0c, 0x1e, 0xce, 0xe9, 0x58, 0x00, 0xe3, 0x81, 0xa4, 0xca,
	0xb3, 0x79, 0x1a, 0x7c, 0x8e, 0xcb, 0x9b, 0x10, 0x54, 0xc0, 0x37, 0x74, 0x8c, 0x2e, 0xa1, 0xa3,
	0xc3, 0x05, 0xfb, 0xa6, 0x60, 0x7f, 0x28, 0x13, 0xab, 0xaa, 0x82, 0xb9, 0xce, 0xca, 0x0d, 0xff,
	0x27, 0x03, 0x8e, 0xae, 0x09, 0x53, 0xf3, 0x57, 0xf3, 0x51, 0x42, 0xe3, 0x2f, 0xc9, 0xe2, 0xd5,
	0xc3, 0xfb, 0x08, 0x60, 0x26, 0xb2, 0x0f, 0xbf, 0x23, 0x0b, 0x01, 0xce, 0xbd, 0x38, 0xd4, 0xd1,
	0xcb, 0xba, 0xa1, 0x33, 0xd3, 0x43, 0xff, 0x37, 0x03, 0x9c, 0x6b, 0xc2, 0xae, 0xe9, 0x34, 0x23,
	0xc5, 0x0e, 0x80, 0x3e, 0x04, 0x5b, 0xd5, 0x53, 0x60, 0xb6, 0xa4, 0xd7, 0x11, 0xe8, 0x03, 0xb0,
	0x4a, 0x91, 0xb8, 0x1e, 0x8a, 0x0a, 0x40, 0xe7, 0x60, 0xcd, 0xf2, 0x84, 0xc6, 0x8b, 0xbe, 0x29,
	0x5a, 0x8a, 0x64, 0x6d, 0x89, 0xeb, 0x4a, 0xcc, 0x84, 0x2a, 0xc2, 0xff, 0xc3, 0x80, 0x0e, 0x6f,
	0xe7, 0x64, 0x42, 0x13, 0x8a, 0x19, 0x79, 0xd5, 0xb0, 0x07, 0xe0, 0x60, 0x9d, 0xfb, 0x8e, 0x26,
	0x2e, 0x63, 0xd0, 0x25, 0xb4, 0x0b, 0x92, 0x60, 0x2e, 0x7b, 0x05, 0xbf, 0xbf, 0xa1, 0x08, 0x8d,
	0x94, 0xe6, 0x59, 0xb8, 0x8c, 0xf4, 0x7f, 0x35, 0xa0, 0x23, 0xe5, 0xfa, 0x0c, 0x27, 0x09, 0xd9,
	0x45, 0xad, 0xf7, 0xa0, 0x85, 0xcb, 0x92, 0x48, 0x12, 0x4e, 0x28, 0x0d, 0x74, 0xb1, 0x12, 0xc9,
	0x9d, 0xcb, 0xae, 0x95, 0xc2, 0xa5, 0xf7, 0x10, 0xdc, 0x5b, 0x51, 0x55, 0xea, 0x58, 0xa2, 0xf6,
	0x64, 0x49, 0x09, 0x47, 0xc8, 0x18, 0x6e, 0x97, 0x63, 0xff, 0x77, 0x03, 0x5c, 0xb5, 0xbd, 0x44,
	0xd9, 0x97, 0xc3, 0x45, 0x60, 0x66, 0x38, 0x25, 0x0a, 0xad, 0x18, 0x73, 0x4d, 0xd0, 0xb2, 0x9c,
	0xdf, 0xa9, 0x09, 0x19, 0xc0, 0x43, 0x97, 0x9a, 0x68, 0xae, 0x6d, 0x33, 0x5e, 0x7d, 0x53, 0x12,
	0xe8, 0x7d, 0xe8, 0xd1, 0x8c, 0x32, 0x8a, 0x93, 0x21, 0x4e, 0xc5, 0x32, 0xb7, 0x4e, 0x8d, 0x33,
	0x33, 0xec, 0x2a, 0xef, 0x63, 0xe1, 0xf4, 0xff, 0x34, 0xa0, 0xf5, 0x05, 0x4f, 0xfe, 0xbf, 0x7b,
	0x7d, 0x1f, 0x2c, 0x55, 0xa0, 0x29, 0x0a, 0x28, 0x0b, 0xbd, 0x03, 0x4e, 0x41, 0x26, 0xa4, 0x20,
	0x59, 0x2c, 0xbb, 0xe9, 0x84, 0x2b, 0x07, 0xcf, 0x95, 0xe5, 0x7c, 0x46, 0xa2, 0x92, 0x06, 0xfa,
	0x18, 0x9c, 0xe5, 0x11, 0xdb, 0xb7, 0x04, 0x90, 0x93, 0x40, 0x1e, 0xc2, 0x81, 0x3e, 0x84, 0x83,
	0x48, 0x47, 0x84, 0xab, 0x60, 0xff, 0x6f, 0x03, 0xda, 0xcf, 0x28, 0xbb, 0x19, 0x17, 0xf8, 0x76,
	0x07, 0x2a, 0x7d, 0xb0, 0xf1, 0x78, 0x5c, 0x90, 0xb2, 0x54, 0x64, 0xb4, 0xb9, 0x22, 0xd9, 0xdc,
	0x4e, 0xd2, 0xac, 0x27, 0xd9, 0xaa, 0x25, 0x69, 0xd5, 0x92, 0xb4, 0xf7, 0x21, 0xf9, 0x8f, 0x01,
	0xbd, 0xeb, 0x45, 0xc9, 0x48, 0x2a, 0xae, 0x95, 0xc9, 0x4e, 0xe7, 0x13, 0x02, 0x73, 0x52, 0xe4,
	0xa9, 0x96, 0x1c, 0x1f, 0xa3, 0x1e, 0x34, 0x58, 0xae, 0x18, 0x36, 0x58, 0xbe, 0x22, 0x6d, 0x6e,
	0x27, 0xdd, 0xaa, 0x27, 0x6d, 0xd5, 0x92, 0xb6, 0x6b, 0x49, 0xb7, 0xf7, 0x21, 0xfd, 0xaf, 0x01,
	0xf6, 0x15, 0x5e, 0xa4, 0x24, 0x63, 0xaf, 0x85, 0xad, 0x07, 0xcd, 0x09, 0xd1, 0x4b, 0xc8, 0x87,
	0x9b, 0xfc, 0xed, 0x5a, 0xfe, 0xed, 0x5a, 0xfe, 0xce, 0x3e, 0xfc, 0x7f, 0x31, 0xe0, 0x60, 0xed,
	0x90, 0xb9, 0xc2, 0x74, 0x97, 0x55, 0x5f, 0x7b, 0x8f, 0x34, 0x76, 0x79, 0x8f, 0x20, 0x30, 0x47,
	0xb8, 0x24, 0xaa, 0x4b, 0x62, 0xcc, 0x99, 0x7c, 0x3f, 0xcf, 0x99, 0xde, 0xbd, 0xd2, 0x40, 0x6f,
	0x83, 0xc3, 0x67, 0x87, 0x05, 0xbf, 0x0b, 0x78, 0xab, 0x1a, 0x61, 0x9b, 0x3b, 0x42, 0xcc, 0x88,
	0xff, 0x83, 0x01, 0xf6, 0x35, 0x61, 0xe1, 0x6e, 0x77, 0x10, 0x02, 0x73, 0x86, 0x69, 0xa1, 0x17,
	0x8b, 0x8f, 0xb9, 0xaf, 0xd0, 0xb7, 0x4c, 0x23, 0x14, 0xe3, 0xcd, 0xe6, 0x99, 0xfb, 0x34, 0xef,
	0x2f, 0x03, 0x8e, 0x9e, 0xe0, 0x0c, 0x4f, 0xc9, 0x67, 0x55, 0x7c, 0x83, 0xb3, 0x29, 0xf9, 0xba,
	0x18, 0xef, 0xb4, 0x6d, 0xee, 0x83, 0x25, 0x4f, 0x7a, 0x85, 0x4e, 0x59, 0x4b, 0xcc, 0xe6, 0x1a,
	0xe6, 0x3a, 0xe9, 0x68, 0x2e, 0x56, 0x1d, 0x97, 0x7d, 0x76, 0xff, 0xf9, 0xcf, 0x0d, 0x38, 0x78,
	0x61, 0xf9, 0xd0, 0x9b, 0x70, 0xf4, 0x82, 0x8b, 0xbf, 0x0d, 0xbd, 0x37, 0xd0, 0x11, 0x1c, 0x44,
	0xd5, 0xc6, 0xd3, 0xcf, 0x33, 0xd0, 0x5b, 0x70, 0x1c, 0x55, 0x5b, 0x9e, 0x5d, 0x5e, 0x03, 0x21,
	0xe8, 0xc9, 0x29, 0x7d, 0x85, 0x7b, 0x4d, 0x74, 0x00, 0xae, 0xf0, 0xc9, 0x27, 0x87, 0x67, 0xa2,
	0x43, 0xe8, 0x2e, 0x93, 0x72, 0x2d, 0x7a, 0x2d, 0xf9, 0xdf, 0xfa, 0x9d, 0xed, 0x59, 0xc8, 0x05,
	0x3b, 0xaa, 0xc4, 0xa5, 0xe2, 0xd9, 0xa8, 0x07, 0x10, 0x55, 0xfa, 0x64, 0xf6, 0xda, 0xe8, 0x1e,
	0x78, 0x51, 0xb5, 0x79, 0x88, 0x79, 0x0e, 0xea, 0x82, 0x13, 0x55, 0x6a, 0x97, 0x7b, 0x80, 0x8e,
	0xe1, 0x70, 0xa3, 0x10, 0x17, 0xbd, 0xe7, 0xca, 0x28, 0x25, 0x2f, 0xaf, 0x23, 0xe9, 0x6c, 0x59,
	0x5d, 0xaf, 0xfb, 0xc9, 0xa3, 0x6f, 0x1f, 0x4e, 0x29, 0x4b, 0xf0, 0x28, 0xa0, 0x59, 0x76, 0x59,
	0xc6, 0x94, 0x6f, 0xcd, 0x20, 0xce, 0xd3, 0xc1, 0xf3, 0x78, 0x3a, 0xe0, 0xab, 0xfd, 0x20, 0x4e,
	0x28, 0xc9, 0x98, 0x18, 0x0f, 0xc4, 0xa3, 0x7f, 0x64, 0x89, 0xfe, 0x3f, 0xfa, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x74, 0x07, 0x17, 0xb6, 0x24, 0x0c, 0x00, 0x00,
}
