// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package testTypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountType int32

const (
	AccountType_AccountTypeNull AccountType = 0
	AccountType_SYSTEM          AccountType = 1
	AccountType_GENERAL         AccountType = 2
	AccountType_MERCHANT        AccountType = 3
)

var AccountType_name = map[int32]string{
	0: "AccountTypeNull",
	1: "SYSTEM",
	2: "GENERAL",
	3: "MERCHANT",
}
var AccountType_value = map[string]int32{
	"AccountTypeNull": 0,
	"SYSTEM":          1,
	"GENERAL":         2,
	"MERCHANT":        3,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{0}
}

type AccountState int32

const (
	AccountState_AccountStateNull AccountState = 0
	AccountState_PENDING          AccountState = 1
	AccountState_ACTIVE           AccountState = 2
	AccountState_INACTIVE         AccountState = 3
	AccountState_BLOCKED          AccountState = 4
)

var AccountState_name = map[int32]string{
	0: "AccountStateNull",
	1: "PENDING",
	2: "ACTIVE",
	3: "INACTIVE",
	4: "BLOCKED",
}
var AccountState_value = map[string]int32{
	"AccountStateNull": 0,
	"PENDING":          1,
	"ACTIVE":           2,
	"INACTIVE":         3,
	"BLOCKED":          4,
}

func (x AccountState) String() string {
	return proto.EnumName(AccountState_name, int32(x))
}
func (AccountState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{1}
}

type AccountAffiliation int32

const (
	AccountAffiliation_AccountAffiliationNull AccountAffiliation = 0
	AccountAffiliation_NotAffiliate           AccountAffiliation = 1
	AccountAffiliation_Creator                AccountAffiliation = 2
	AccountAffiliation_Referrer               AccountAffiliation = 3
)

var AccountAffiliation_name = map[int32]string{
	0: "AccountAffiliationNull",
	1: "NotAffiliate",
	2: "Creator",
	3: "Referrer",
}
var AccountAffiliation_value = map[string]int32{
	"AccountAffiliationNull": 0,
	"NotAffiliate":           1,
	"Creator":                2,
	"Referrer":               3,
}

func (x AccountAffiliation) String() string {
	return proto.EnumName(AccountAffiliation_name, int32(x))
}
func (AccountAffiliation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{2}
}

type SignerPolicy int32

const (
	SignerPolicy_SignerPolicyNull SignerPolicy = 0
	SignerPolicy_NotSigner        SignerPolicy = 1
	SignerPolicy_Master           SignerPolicy = 2
)

var SignerPolicy_name = map[int32]string{
	0: "SignerPolicyNull",
	1: "NotSigner",
	2: "Master",
}
var SignerPolicy_value = map[string]int32{
	"SignerPolicyNull": 0,
	"NotSigner":        1,
	"Master":           2,
}

func (x SignerPolicy) String() string {
	return proto.EnumName(SignerPolicy_name, int32(x))
}
func (SignerPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{3}
}

type AssetPolicy int32

const (
	AssetPolicy_AssetPolicyNull   AssetPolicy = 0
	AssetPolicy_AssetIssuable     AssetPolicy = 1
	AssetPolicy_AssetTransferable AssetPolicy = 2
	AssetPolicy_AssetWithdrawable AssetPolicy = 3
	AssetPolicy_AssetExchangeable AssetPolicy = 4
)

var AssetPolicy_name = map[int32]string{
	0: "AssetPolicyNull",
	1: "AssetIssuable",
	2: "AssetTransferable",
	3: "AssetWithdrawable",
	4: "AssetExchangeable",
}
var AssetPolicy_value = map[string]int32{
	"AssetPolicyNull":   0,
	"AssetIssuable":     1,
	"AssetTransferable": 2,
	"AssetWithdrawable": 3,
	"AssetExchangeable": 4,
}

func (x AssetPolicy) String() string {
	return proto.EnumName(AssetPolicy_name, int32(x))
}
func (AssetPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{4}
}

type WalletType int32

const (
	WalletType_WalletTypeNull WalletType = 0
	// void
	WalletType_AssetVoid WalletType = 1
	// regular asset holder, user wallet
	WalletType_AssetHolder WalletType = 2
	// hold pre-emitted asset amount, system wallet
	WalletType_AssetIssuer WalletType = 3
	// transfer fee holder, system wallet
	WalletType_AssetFeeHolder WalletType = 4
	// todo: ???
	WalletType_AssetMarket WalletType = 5
)

var WalletType_name = map[int32]string{
	0: "WalletTypeNull",
	1: "AssetVoid",
	2: "AssetHolder",
	3: "AssetIssuer",
	4: "AssetFeeHolder",
	5: "AssetMarket",
}
var WalletType_value = map[string]int32{
	"WalletTypeNull": 0,
	"AssetVoid":      1,
	"AssetHolder":    2,
	"AssetIssuer":    3,
	"AssetFeeHolder": 4,
	"AssetMarket":    5,
}

func (x WalletType) String() string {
	return proto.EnumName(WalletType_name, int32(x))
}
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{5}
}

type OrderType int32

const (
	OrderType_OrderTypeNull OrderType = 0
	OrderType_Ask           OrderType = 1
	OrderType_Bid           OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "OrderTypeNull",
	1: "Ask",
	2: "Bid",
}
var OrderType_value = map[string]int32{
	"OrderTypeNull": 0,
	"Ask":           1,
	"Bid":           2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{6}
}

type OrderState int32

const (
	OrderState_OrderStateNull OrderState = 0
	OrderState_PendingOrder   OrderState = 1
	OrderState_FulfilledOrder OrderState = 2
	OrderState_CanceledOrder  OrderState = 3
)

var OrderState_name = map[int32]string{
	0: "OrderStateNull",
	1: "PendingOrder",
	2: "FulfilledOrder",
	3: "CanceledOrder",
}
var OrderState_value = map[string]int32{
	"OrderStateNull": 0,
	"PendingOrder":   1,
	"FulfilledOrder": 2,
	"CanceledOrder":  3,
}

func (x OrderState) String() string {
	return proto.EnumName(OrderState_name, int32(x))
}
func (OrderState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{7}
}

type WalletAddress struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletAddress) Reset()         { *m = WalletAddress{} }
func (m *WalletAddress) String() string { return proto.CompactTextString(m) }
func (*WalletAddress) ProtoMessage()    {}
func (*WalletAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_e7aacfa836816276, []int{0}
}
func (m *WalletAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletAddress.Unmarshal(m, b)
}
func (m *WalletAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletAddress.Marshal(b, m, deterministic)
}
func (dst *WalletAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletAddress.Merge(dst, src)
}
func (m *WalletAddress) XXX_Size() int {
	return xxx_messageInfo_WalletAddress.Size(m)
}
func (m *WalletAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletAddress.DiscardUnknown(m)
}

var xxx_messageInfo_WalletAddress proto.InternalMessageInfo

func (m *WalletAddress) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*WalletAddress)(nil), "node.WalletAddress")
	proto.RegisterEnum("node.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("node.AccountState", AccountState_name, AccountState_value)
	proto.RegisterEnum("node.AccountAffiliation", AccountAffiliation_name, AccountAffiliation_value)
	proto.RegisterEnum("node.SignerPolicy", SignerPolicy_name, SignerPolicy_value)
	proto.RegisterEnum("node.AssetPolicy", AssetPolicy_name, AssetPolicy_value)
	proto.RegisterEnum("node.WalletType", WalletType_name, WalletType_value)
	proto.RegisterEnum("node.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("node.OrderState", OrderState_name, OrderState_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_e7aacfa836816276) }

var fileDescriptor_types_e7aacfa836816276 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0x49, 0x53, 0x36, 0x76, 0xdb, 0x6e, 0xae, 0xf9, 0x23, 0xc4, 0x13, 0x82, 0x17, 0x14,
	0x89, 0x16, 0x34, 0xde, 0x51, 0xda, 0x65, 0x5b, 0xc5, 0x9a, 0x55, 0x6d, 0xb5, 0x31, 0x24, 0x1e,
	0xdc, 0xe4, 0xb6, 0xb3, 0x66, 0xec, 0xca, 0x76, 0x07, 0xe5, 0xd3, 0x23, 0x3b, 0x56, 0x5a, 0x89,
	0x37, 0x9f, 0x5f, 0xee, 0x3d, 0xf7, 0xc8, 0xce, 0x85, 0x96, 0xdd, 0xae, 0xd1, 0xf4, 0xd6, 0x5a,
	0x59, 0x45, 0x9b, 0x52, 0x95, 0xf8, 0xee, 0x3d, 0x74, 0x6e, 0x99, 0x10, 0x68, 0xd3, 0xb2, 0xd4,
	0x68, 0x0c, 0xa5, 0xd0, 0x2c, 0x99, 0x65, 0xaf, 0xa3, 0xb7, 0xd1, 0x87, 0xf6, 0xd4, 0x9f, 0x93,
	0x11, 0xb4, 0xd2, 0xa2, 0x50, 0x1b, 0x69, 0xe7, 0xdb, 0x35, 0xd2, 0xe7, 0x70, 0xb2, 0x27, 0xf3,
	0x8d, 0x10, 0xe4, 0x09, 0x05, 0x38, 0x98, 0xdd, 0xcd, 0xe6, 0xd9, 0x98, 0x44, 0xb4, 0x05, 0x87,
	0x17, 0x59, 0x9e, 0x4d, 0xd3, 0x2b, 0xd2, 0xa0, 0x6d, 0x78, 0x36, 0xce, 0xa6, 0xc3, 0xcb, 0x34,
	0x9f, 0x93, 0x38, 0xf9, 0x0e, 0xed, 0xd0, 0x3b, 0xb3, 0xcc, 0x22, 0x7d, 0x01, 0x64, 0x5f, 0x07,
	0xb3, 0x16, 0x1c, 0x4e, 0xb2, 0xfc, 0x6c, 0x94, 0x5f, 0x90, 0xc8, 0x39, 0xa7, 0xc3, 0xf9, 0xe8,
	0x26, 0xab, 0xcc, 0x46, 0x79, 0x50, 0xb1, 0x2b, 0x1b, 0x5c, 0x5d, 0x0f, 0xbf, 0x65, 0x67, 0xa4,
	0x99, 0xfc, 0x04, 0x1a, 0x9c, 0xd2, 0xe5, 0x92, 0x0b, 0xce, 0x2c, 0x57, 0x92, 0xbe, 0x81, 0x57,
	0xff, 0xd3, 0x30, 0x85, 0x40, 0x3b, 0x57, 0x35, 0xc7, 0x2a, 0xf8, 0x50, 0x23, 0xb3, 0x4a, 0x57,
	0xb3, 0xa6, 0xb8, 0x44, 0xad, 0x51, 0x93, 0x38, 0xf9, 0x0a, 0xed, 0x19, 0x5f, 0x49, 0xd4, 0x13,
	0x25, 0x78, 0xb1, 0x75, 0xc1, 0xf7, 0x75, 0xb0, 0xec, 0xc0, 0x51, 0xae, 0x6c, 0xf5, 0xa1, 0x8a,
	0x3e, 0x66, 0xc6, 0xa2, 0x26, 0x8d, 0xe4, 0x2f, 0xb4, 0x52, 0x63, 0xd0, 0x86, 0x7e, 0x77, 0x89,
	0x3b, 0x19, 0xda, 0xbb, 0xd0, 0xf1, 0x70, 0x64, 0xcc, 0x86, 0x2d, 0x84, 0x8b, 0xf4, 0x12, 0xba,
	0x1e, 0xcd, 0x35, 0x93, 0x66, 0x89, 0xda, 0xe3, 0x46, 0x8d, 0x6f, 0xb9, 0xbd, 0x2f, 0x35, 0xfb,
	0xed, 0x71, 0x5c, 0xe3, 0xec, 0x4f, 0x71, 0xcf, 0xe4, 0x0a, 0x3d, 0x6e, 0x26, 0x8f, 0x00, 0xd5,
	0x2b, 0xfb, 0xf7, 0xa3, 0x70, 0xbc, 0x53, 0xbb, 0xe0, 0xbe, 0xf1, 0x46, 0xf1, 0x92, 0x44, 0xf4,
	0x24, 0x84, 0xbd, 0x54, 0xa2, 0x74, 0xe9, 0x6b, 0xe0, 0x92, 0xb9, 0xfb, 0x70, 0x26, 0x1e, 0x9c,
	0x23, 0x86, 0xa2, 0x66, 0x5d, 0x34, 0x66, 0xfa, 0x01, 0x2d, 0x79, 0x9a, 0x7c, 0x82, 0xa3, 0x6b,
	0x5d, 0xa2, 0xf6, 0x63, 0xbb, 0xd0, 0xa9, 0x45, 0x98, 0x7a, 0x08, 0x71, 0x6a, 0x1e, 0x48, 0xe4,
	0x0e, 0x03, 0x5e, 0x92, 0x46, 0x72, 0x07, 0xe0, 0x8b, 0xaa, 0xbf, 0x83, 0xc2, 0xf1, 0x4e, 0xed,
	0x5e, 0x6d, 0x82, 0xb2, 0xe4, 0x72, 0xe5, 0x3f, 0x91, 0xc8, 0x55, 0x9d, 0x6f, 0xc4, 0x92, 0x0b,
	0x81, 0x65, 0xc5, 0x1a, 0x6e, 0xd8, 0x90, 0xc9, 0x02, 0x6b, 0x14, 0x0f, 0x4e, 0x7f, 0x7c, 0x5e,
	0x71, 0x2b, 0xd8, 0xa2, 0xc7, 0xa5, 0xfc, 0x62, 0x0a, 0x8e, 0xb2, 0xc0, 0x5e, 0xa1, 0x7e, 0xf5,
	0x1f, 0x8b, 0x55, 0xdf, 0x6d, 0xc3, 0xc7, 0x42, 0x70, 0x94, 0xd6, 0x9f, 0xfb, 0x7e, 0x57, 0x16,
	0x07, 0x7e, 0x59, 0x4e, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x22, 0x9a, 0x06, 0xca, 0x3b, 0x03,
	0x00, 0x00,
}
